name: 'IPFS All-in-One Publisher'
description: 'Pin and publish your folder to IPFS'
author: 'Piotr Węgrzyn <piotr@wegrzyn.dev>'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  upload_path:
    description: 'File/directory path to add to IPFS'
    required: true
  remote_service_name:
    description: 'Name of pinning service'
    required: true
  remote_service_endpoint:
    description: 'API URL of pinning service'
    required: true
  remote_service_key:
    description: 'Key/access token to pinning service'
    required: true
  publish_key_name:
    description: 'IPNS key name'
    required: true
  publish_key_value:
    description: 'IPNS key value (pem-pkcs8-cleartext format)'
    required: true
outputs:
  cid:
    description: 'IPFS Content ID of the pinned file/directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    UPLOAD_PATH: ${{ inputs.upload_path }}
    REMOTE_SERVICE_NAME: ${{ inputs.remote }}
    REMOTE_SERVICE_ENDPOINT: ${{ inputs.endpoint }}
    REMOTE_SERVICE_KEY: ${{ inputs.access_token }}
    PUBLISH_KEY_NAME: ${{ inputs.publish_key_name }}
    PUBLISH_KEY_VALUE: ${{ inputs.publish_key_value }}
  